development:
  adapter: postgresql
  database: swag_development
  encoding: unicode
  user: wikiful
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: swag_test
  encoding: unicode
  user: wikiful
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: swag_production
  encoding: unicode
  pool: 5
  timeout: 5000
